AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'lib/valkey/protobuf/**/*.rb'

Style/StringLiterals:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/valkey.rb'
    - 'test/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/valkey/request_type.rb'
    - 'test/**/*.rb'

